# Generated by Django 5.1.7 on 2025-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='duration',
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Подтверждено'), ('issued', 'Выдано'), ('returned', 'Возвращено'), ('rejected', 'Отклонено'), ('in_repair', 'В ремонте')], default='pending', max_length=10),
        ),
    ]
