# Generated by Django 5.2 on 2025-05-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_rentalcontract_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcheck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата завершения/обновления'),
        ),
        migrations.AlterField(
            model_name='equipmentcheck',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает проверки'), ('checked_ok', 'Проверено, исправно'), ('needs_repair', 'Требуется ремонт'), ('repaired', 'Ремонт завершён')], default='pending', max_length=20),
        ),
    ]
