# Generated by Django 5.2 on 2025-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_equipmentcheck_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrepair',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения ремонта'),
        ),
    ]
